spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ?? : create, update, create-drop, validate, none
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true